import { useRef } from "react";
import { ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";
import { processSteps, professionalHistory, profileImage, serviceCategories, siteConfig, testimonials } from "../data/siteContent";
import { formatRange, shortTimeline } from "./format";
import LottieIcon from "./LottieIcon";

// Generated by scripts/generate-process-lottie.mjs; loaded on demand as separate chunks.
const processAnimations = {
  Discover: () => import("../assets/lottie/process-discover.json"),
  Plan: () => import("../assets/lottie/process-plan.json"),
  Build: () => import("../assets/lottie/process-build.json"),
  Launch: () => import("../assets/lottie/process-launch.json"),
};

export function HeroOrbs() {
  return (
    <div className="hero-orbs" aria-hidden="true">
      <span className="orb orb-a" data-depth="46" />
      <span className="orb orb-b" data-depth="-34" />
    </div>
  );
}

export function HeroPortrait({ caption = "WordPress / GoHighLevel / Frontend", badge = "Remote, worldwide" }) {
  return (
    <div className="portrait-wrap rise" style={{ "--d": "120ms" }}>
      <div className="halo" aria-hidden="true" data-depth="-22" />
      <figure className="portrait" data-tilt-portrait>
        <span className="glare" aria-hidden="true" />
        <img src={profileImage} alt="Janrenzo Facto in a light gray suit" width="1200" height="1461" fetchPriority="high" />
        <figcaption className="portrait-meta">
          <p><strong>{siteConfig.name}</strong>{caption}</p>
          <span className="glass"><i aria-hidden="true" />{badge}</span>
        </figcaption>
      </figure>
    </div>
  );
}

export function ServicesList() {
  return (
    <>
      <div className="rows reveal">
        {serviceCategories.map((service, index) => (
          <Link key={service.id} to={`/services#${service.id}`} className="svc">
            <span className="num">0{index + 1}</span>
            <h3>{service.title}</h3>
            <p>{service.summary}</p>
            <span className="time">{shortTimeline(service.timeline)}</span>
            <span className="price">{formatRange(service.priceBand)}<small>Starting range</small></span>
            <ArrowRight className="arrow" aria-hidden="true" />
          </Link>
        ))}
      </div>
      <p className="rows-note">Final quotes depend on scope, content, integrations, and revisions.</p>
    </>
  );
}

function ProcessStep({ step, index }) {
  const iconRef = useRef(null);
  const loadAnimation = processAnimations[step.title];

  return (
    <li className="step reveal" style={{ "--delay": `${index * 90}ms` }} onMouseEnter={() => iconRef.current?.replay()}>
      <span className="step-icon">
        {loadAnimation && <LottieIcon ref={iconRef} loadAnimation={loadAnimation} delay={index * 140} className="process-icon-player" />}
      </span>
      <span className="num">0{index + 1}</span>
      <h3>{step.title}</h3>
      <p>{step.text}</p>
    </li>
  );
}

export function ProcessSection() {
  return (
    <section className="section" aria-labelledby="process-title">
      <div className="wrap">
        <div className="section-head reveal">
          <div>
            <p className="kicker">Process</p>
            <h2 className="h2" id="process-title">A clear path from idea to launch.</h2>
            <p className="lead">Each phase has a purpose, a decision to make, and a visible deliverable before the project moves forward.</p>
          </div>
        </div>
        <ol className="steps">
          {processSteps.map((step, index) => <ProcessStep key={step.title} step={step} index={index} />)}
        </ol>
      </div>
    </section>
  );
}

export function TestimonialsSection() {
  if (testimonials.length === 0) return null;

  return (
    <section className="section" aria-labelledby="testimonials-title">
      <div className="wrap">
        <div className="section-head reveal">
          <div>
            <p className="kicker">Client feedback</p>
            <h2 className="h2" id="testimonials-title">What working together is like.</h2>
          </div>
        </div>
        <div className="quotes">
          {testimonials.map((item) => (
            <figure key={`${item.name}-${item.quote.slice(0, 24)}`} className="quote reveal">
              <span className="mark" aria-hidden="true">“</span>
              <blockquote>{item.quote}</blockquote>
              <figcaption>
                <strong>{item.name}</strong>
                {[item.role, item.company].filter(Boolean).join(", ")}
                {item.projectId && <> · <Link to={`/portfolio/${item.projectId}`}>View the project</Link></>}
              </figcaption>
            </figure>
          ))}
        </div>
      </div>
    </section>
  );
}

export function ExperienceList({ withNotes = false }) {
  return (
    <ol className="xp" aria-label="Experience">
      {professionalHistory.map((item) => (
        <li key={`${item.period}-${item.role}`}>
          <span className="when">{item.period}</span>
          <div>
            <p className="role">{item.role}</p>
            <p className="org">{item.company}</p>
            {withNotes && <p className="note">{item.text}</p>}
          </div>
        </li>
      ))}
    </ol>
  );
}

export function FinalCta({
  kicker = "Start a project",
  title = "Have a project in mind?",
  text = "Let's turn it into something clear, premium, and ready to grow. Share the goal and the context that matters, and I'll reply with a practical next step.",
  primary = { to: "/contact", label: "Start a project" },
  secondary = { to: "/portfolio", label: "Review the work" },
}) {
  return (
    <section className="cta" aria-labelledby="cta-title">
      <div className="wrap reveal">
        <p className="kicker">{kicker}</p>
        <h2 id="cta-title">{title}</h2>
        <p className="cta-text">{text}</p>
        <div className="ctas">
          <Link to={primary.to} className="btn btn-accent">{primary.label} <ArrowRight aria-hidden="true" /></Link>
          <Link to={secondary.to} className="btn btn-ghost">{secondary.label}</Link>
        </div>
        <a className="mail" href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>
        <p className="reply">{siteConfig.responseTime} · Available worldwide</p>
      </div>
    </section>
  );
}
