import { useRef } from "react";
import { Link } from "react-router-dom";
import { processSteps, serviceCategories, testimonials } from "../data/siteContent";
import ConnectorLinework from "./ConnectorLinework";
import LottieIcon from "./LottieIcon";

// Generated by scripts/generate-process-lottie.mjs; loaded on demand as separate chunks.
const processAnimations = {
  Discover: () => import("../assets/lottie/process-discover.json"),
  Plan: () => import("../assets/lottie/process-plan.json"),
  Build: () => import("../assets/lottie/process-build.json"),
  Launch: () => import("../assets/lottie/process-launch.json"),
};

export function ServicesOverview({ detailed = false }) {
  return (
    <div className="grid min-w-0 gap-4 lg:grid-cols-3">
      {serviceCategories.map((service, index) => (
        <article key={service.id} className="service-card surface-card surface-card-interactive flex min-w-0 flex-col p-6 sm:p-7">
          <div className="flex items-center justify-between gap-4">
            <span className="service-card-number text-sm font-bold text-lime-300">0{index + 1}</span>
            <span className="tag">{service.timeline.split(":")[1]?.split(",")[0]?.trim() || service.timeline}</span>
          </div>
          <h3 className="service-card-title mt-8 text-2xl font-bold leading-tight">{service.title}</h3>
          <p className="mt-4 leading-7 text-white/70">{service.summary}</p>

          <div className="mt-7 border-t border-white/10 pt-5">
            <p className="text-xs font-bold uppercase tracking-[0.12em] text-white/65">Best for</p>
            <p className="mt-2 text-sm leading-6 text-white/60">{service.idealFor}</p>
          </div>

          <div className="mt-6">
            <p className="text-xs font-bold uppercase tracking-[0.12em] text-white/65">Included</p>
            <ul className="mt-3 grid gap-2 text-sm leading-6 text-white/65">
              {service.includes.slice(0, detailed ? service.includes.length : 3).map((item) => <li key={item} className="flex gap-3"><span className="text-lime-300">+</span><span>{item}</span></li>)}
            </ul>
          </div>

          <div className="mt-auto pt-7">
            <p className="text-xs font-bold uppercase tracking-[0.12em] text-white/65">Deliverables</p>
            <p className="mt-2 text-sm leading-6 text-white/60">{service.deliverables}</p>
            {detailed && (
              <>
                <div className="service-card-pricing mt-6 border-y border-white/10 py-4">
                  <p className="text-xs font-bold uppercase tracking-[0.12em] text-white/65">Typical starting range</p>
                  <p className="mt-2 text-2xl font-bold text-lime-200">{service.priceBand}</p>
                  <p className="mt-1 text-xs leading-5 text-white/65">{service.timeline}</p>
                </div>
                <p className="mt-4 text-xs leading-5 text-white/65">Final quote depends on scope, content, integrations, and revisions.</p>
                <Link to="/contact" aria-label={`Discuss ${service.title}`} className="button-secondary mt-6 w-full focus-ring">
                  Discuss this service
                </Link>
              </>
            )}
          </div>
        </article>
      ))}
    </div>
  );
}

function ProcessStep({ step, index, light }) {
  const iconRef = useRef(null);
  const loadAnimation = processAnimations[step.title];

  return (
    <li onMouseEnter={() => iconRef.current?.replay()} className={`process-step grid gap-4 border-b py-7 sm:grid-cols-[5rem_0.55fr_1fr] sm:items-start ${light ? "border-black/15" : "border-white/10"}`}>
      <span aria-hidden="true" className={`process-step-node ${light ? "is-light" : ""}`} />
      <span className={`text-sm font-bold ${light ? "text-[#568400]" : "text-lime-300"}`}>0{index + 1}</span>
      <div className="process-step-heading">
        {loadAnimation && (
          <span className={`process-icon ${light ? "is-light" : ""}`}>
            <LottieIcon ref={iconRef} loadAnimation={loadAnimation} delay={index * 140} className="process-icon-player" />
          </span>
        )}
        <h3 className="text-xl font-bold">{step.title}</h3>
      </div>
      <p className={`leading-7 ${light ? "text-black/70" : "text-white/70"}`}>{step.text}</p>
    </li>
  );
}

export function ProcessSection({ light = false }) {
  return (
    <section className={light ? "site-section bg-[#f3f4ee] text-black" : "site-section bg-[#0a0b09] text-white"}>
      <div className="site-container grid gap-12 lg:grid-cols-[0.72fr_1.28fr]">
        <div>
          <p className={`section-kicker ${light ? "text-[#568400]" : ""}`}>Process</p>
          <h2 className="section-title">A clear path from idea to launch.</h2>
          <p className={`mt-6 max-w-lg text-lg leading-8 ${light ? "text-black/70" : "text-white/70"}`}>
            Each phase has a purpose, a decision to make, and a visible deliverable before the project moves forward.
          </p>
        </div>

        <ol className={`process-list relative border-t ${light ? "border-black/15" : "border-white/10"}`}>
          <ConnectorLinework variant="process" />
          {processSteps.map((step, index) => <ProcessStep key={step.title} step={step} index={index} light={light} />)}
        </ol>
      </div>
    </section>
  );
}

export function TestimonialsSection() {
  if (testimonials.length === 0) return null;

  return (
    <section aria-labelledby="testimonials-title" className="site-section border-t border-white/10 bg-[#0b0c0a] text-white">
      <div className="site-container">
        <p className="section-kicker">Client feedback</p>
        <h2 id="testimonials-title" className="section-title">What working together is like.</h2>
        <div className="mt-12 grid min-w-0 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {testimonials.map((item) => (
            <figure key={`${item.name}-${item.quote.slice(0, 24)}`} className="surface-card flex min-w-0 flex-col p-6 sm:p-7">
              <span aria-hidden="true" className="text-5xl font-bold leading-none text-lime-300">&ldquo;</span>
              <blockquote className="mt-3 flex-1 text-lg leading-8 text-white/80">{item.quote}</blockquote>
              <figcaption className="mt-7 border-t border-white/10 pt-5">
                <p className="font-bold">{item.name}</p>
                <p className="mt-1 text-sm text-white/65">{[item.role, item.company].filter(Boolean).join(", ")}</p>
                {item.projectId && (
                  <Link to={`/portfolio/${item.projectId}`} className="project-action mt-3 inline-flex min-h-11 items-center text-sm font-bold text-white underline decoration-lime-300 decoration-2 underline-offset-4 focus-ring">
                    View the Project
                  </Link>
                )}
              </figcaption>
            </figure>
          ))}
        </div>
      </div>
    </section>
  );
}

export function FinalCta() {
  return (
    <section className="bg-lime-300 py-16 text-black sm:py-20">
      <div className="site-container grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end">
        <div>
          <p className="text-sm font-bold uppercase tracking-[0.12em] text-black/55">Have an idea?</p>
          <h2 className="mt-5 max-w-4xl text-4xl font-bold leading-tight sm:text-6xl">
            Let's turn it into something clear, premium, and ready to grow.
          </h2>
        </div>
        <div className="flex flex-col gap-3 sm:flex-row lg:flex-col">
          <Link to="/contact" className="button-primary bg-black text-lime-300 hover:bg-white hover:text-black">Start a Project</Link>
          <Link to="/portfolio" className="button-secondary border-black/25 bg-transparent text-black hover:border-black hover:bg-black hover:text-white">View My Work</Link>
        </div>
      </div>
    </section>
  );
}
